services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    container_name: statify-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: statify-backend
    ports:
      - "5000:5000"
    volumes:
      - temp_data:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=5000
      - NEXT_PUBLIC_FRONTEND_URL=https://statify-dev.student.stis.ac.id
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  temp_data: