services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: statify-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - BACKEND_URL=http://api.statify-dev.student.stis.ac.id
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: statify-backend
    ports:
      - "5000:5000"
    volumes:
      - temp_data:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=https://statify-dev.student.stis.ac.id
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/sav"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  temp_data: